export const ROUTES = {
    HOME: '/',
    ABOUT: '/about-us',
    PRICING: '/pricing',
    CONTACT: '/contact',
    LOGIN: '/login',
    REGISTER: '/register',
    FORGOT_PASSWORD: '/forgot-password',
    VERIFY_CODE: '/verify-code',
    RESET_PASSWORD: '/reset-password',
    DASHBOARD: '/dashboard',
    ORDER_ADD: '/order/add',
    ORDER_EDIT: '/orders/:orderId',
    ORDER_COUNTRY_SELECTION: '/order/package',
    ORDER_PAYMENT: '/order/payment',
    ORDER_PAYMENT_WITH_ID: '/order/payment/:id',
    ORDER_UPGRADE_WITH_ID: '/order/upgrade/:id',
    MARKETPLACE: '/marketplace',
    AFFILIATE_PROGRAM: '/referrals',
    SETTINGS: '/settings',
    ORDERS: '/orders',
    INBOX: '/inbox',
    LOGOUT: '/logout',
    // Admin routes
    ADMIN_LOGIN: '/admin/login',
    ADMIN_DASHBOARD: '/admin/dashboard',
    ADMIN_ORDERS: '/admin/orders',
    ADMIN_USERS: '/admin/users',
    ADMIN_COMPANIES: '/admin/companies',
    ADMIN_PAYMENTS: '/admin/payments',
    ADMIN_PRICING_PLANS: '/admin/pricing-plans',
    ADMIN_PROMO_CODES: '/admin/promo-codes',
    ADMIN_MARKETPLACE: '/admin/marketplace',
    ADMIN_AFFILIATES: '/admin/affiliates',
    ADMIN_PAYOUT_REQUESTS: '/admin/payout-requests',
    ADMIN_SUPPORT: '/admin/support',
  } as const;
  
  export type Route = typeof ROUTES[keyof typeof ROUTES];